name: Get Invitation to join the organization
description: I would like to join the college organization
title: "Please invite me to the GECJ GitHub Community"
labels: [invite me to the organisation]
body:
  - type: input
    id: passing-year
    attributes:
      label: Passing Year
      placeholder: Insert your passing year here (e.g. 2023)
    validations:
      required: true
  - type: input
    id: Name
    attributes:
      label: Name
      placeholder: Insert your name here
    validations:
      required: true
  - type: input
    id: Roll
    attributes:
      label: Roll
      placeholder: Insert your roll number here
    validations:
      required: true
  - type: input
    id: Email
    attributes:
      label: Email
      placeholder: Insert your email id here
    validations:
      required: true
  - type: input
    id: username
    attributes:
      label: Github username
      placeholder: Insert your Github username here
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        Please make sure to update your details in [StudentList.json](https://github.com/GEC-Jhalawar/Support/blob/main/utils/StudentList.json) file in case it is not automatically updated.
        Feel free to check out other cool repositories of the GECJ [here](https://github.com/GEC-Jhalawar)
