name: Add to StudentList.json
on:
  workflow_dispatch:
  issues:
    types:
      - labeled
jobs:
  add-student:
    if: github.event.label.name == 'approved-invite'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: GEC-Jhalawar/gh-action-add-students/src/add-student@main
        with:
          github-token: ${{ secrets.MY_TOKEN }}
          file-path: 'utils/StudentList.json'
  automate_invite:
    if: github.event.label.name == 'approved-invite'
    runs-on: ubuntu-latest
    steps:
      - name: Invite on label
        uses: vj-abigo/invite-on-label@v1.2
        with:
          organization: GEC-Jhalawar
          label: approved-invite
          repo-token: ${{ secrets.MY_TOKEN }}
          comment: '<b>Invitation sent to join the GitHub Organisation. Welcome to the community 🎉</b><br><br>Don''t forget after accepting to make it public so it appears on your GitHub profile for everyone else to see. You can do this by finding your name in the GitHub organisation list and change the dropdown to public https://github.com/orgs/GEC-Jhalawar/people<br><br>Remember contributing to open source is not just about code, it''s about collaboration, communication and adding value<br>I hope that helps'
        env:
          INVITE_TOKEN: ${{ secrets.MY_TOKEN }}

    
  # update-files:
  #   if: github.event.label.name == 'approved-invite'
  #   runs-on: ubuntu-latest
  #   steps:
  #   - name: Check out repo
  #     uses: actions/checkout@v2
  #     with:
  #       ref: main
  #   - name: Set up Python
  #     uses: actions/setup-python@v2
  #     with:
  #       python-version: 3.8
  #   - name: Update README
  #     env:
  #       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #     run: |-
  #       python utils/updateREADME.py
  #       cat README.md
  #   - name: Commit and push if README changed
  #     run: |-
  #       git diff
  #       git config --global user.email "aryaraj132@gmail.com"
  #       git config --global user.name "README-bot"
  #       git diff --quiet || (git add README.md && git commit -m "Updated README")
  #       git push