# update README.md file daily
name: Update README.md
on:
  workflow_dispatch:
  push:
    branches: ['main']
    paths: ['utils/**']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@v2
      with:
        ref: main
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Update README
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |-
        python utils/updateREADME.py
        cat README.md
    - name: Commit and push if README changed
      run: |-
        git diff
        git config --global user.email "aryaraj132@gmail.com"
        git config --global user.name "README-bot"
        git diff --quiet || (git add README.md && git commit -m "Updated README")
        git push

